// 海龟 API 文档数据（按 Python 官方文档 turtle 模块生成：https://docs.python.org/zh-cn/3/library/turtle.html）
// 包含模块级函数与 Turtle/Screen 对象方法（按名称去重，模块级优先），供 LSP 补全与签名提示使用

export interface TurtleApiDoc {
  desc: string
  sig: string
}

export const turtleApiDatabase: Record<string, TurtleApiDoc> = {
  'forward': { desc: '海龟前进 distance 指定的距离，方向为海龟的朝向。', sig: 'distance' },
  'fd': { desc: '海龟前进 distance 指定的距离，方向为海龟的朝向。', sig: 'distance' },
  'back': { desc: '海龟后退 distance 指定的距离，方向与海龟的朝向相反。不改变海龟的朝向。', sig: 'distance' },
  'bk': { desc: '海龟后退 distance 指定的距离，方向与海龟的朝向相反。不改变海龟的朝向。', sig: 'distance' },
  'backward': { desc: '海龟后退 distance 指定的距离，方向与海龟的朝向相反。不改变海龟的朝向。', sig: 'distance' },
  'right': { desc: '海龟右转 angle 个单位。(单位默认为角度，但可通过 degrees() 和 radians() 函数改变设置。) 角度的正负由海龟模式确定，参见 mode()。', sig: 'angle' },
  'rt': { desc: '海龟右转 angle 个单位。(单位默认为角度，但可通过 degrees() 和 radians() 函数改变设置。) 角度的正负由海龟模式确定，参见 mode()。', sig: 'angle' },
  'left': { desc: '海龟左转 angle 个单位。(单位默认为角度，但可通过 degrees() 和 radians() 函数改变设置。) 角度的正负由海龟模式确定，参见 mode()。', sig: 'angle' },
  'lt': { desc: '海龟左转 angle 个单位。(单位默认为角度，但可通过 degrees() 和 radians() 函数改变设置。) 角度的正负由海龟模式确定，参见 mode()。', sig: 'angle' },
  'goto': { desc: '如果 y 为 None，x 应为一个表示坐标的数值对或 Vec2D 类对象 (例如 pos() 返回的对象).', sig: 'x, y=None' },
  'setpos': { desc: '如果 y 为 None，x 应为一个表示坐标的数值对或 Vec2D 类对象 (例如 pos() 返回的对象).', sig: 'x, y=None' },
  'setposition': { desc: '如果 y 为 None，x 应为一个表示坐标的数值对或 Vec2D 类对象 (例如 pos() 返回的对象).', sig: 'x, y=None' },
  'teleport': { desc: '将海龟移到某个绝对位置。 不同于 goto(x, y)，这将不会画一条线段。 海龟的方向不变。 如果当前正在填充，离开后原位置上的多边形将被填充，在移位后将再次开始填充。 这可以通过 fill_gap=True 来禁用，此设置将使在移位期间海龟的移动轨迹线像在 goto(x, y) 中一样被当作填充边缘。', sig: 'x, y=None, *, fill_gap=False' },
  'setx': { desc: '设置海龟的横坐标为 x，纵坐标保持不变。', sig: 'x' },
  'sety': { desc: '设置海龟的纵坐标为 y，横坐标保持不变。', sig: 'y' },
  'setheading': { desc: '设置海龟的朝向为 to_angle。以下是以角度表示的几个常用方向', sig: 'to_angle' },
  'seth': { desc: '设置海龟的朝向为 to_angle。以下是以角度表示的几个常用方向', sig: 'to_angle' },
  'home': { desc: '海龟移至初始坐标 (0,0)，并设置朝向为初始方向 (由海龟模式确定，参见 mode())。', sig: '' },
  'circle': { desc: '绘制一个 radius 指定半径的圆。圆心在海龟左边 radius 个单位；extent 为一个夹角，用来决定绘制圆的一部分。如未指定 extent则绘制整个圆。如果 extent 不是完整圆周，则以当前画笔位置为一个端点绘制圆弧。如果 radius 为正值则朝逆时针方向绘制圆弧，否则朝顺时针方向。最终海龟的朝向会依据 extent 的值而改变。', sig: 'radius, extent=None, steps=None' },
  'dot': { desc: '绘制一个直径为 size，颜色为 color 的圆点。 如果未给出 size，则使用 pensize+4 和 2pensize 中的较大值。', sig: 'size' },
  'stamp': { desc: '在海龟当前位置印制一个海龟形状。返回该印章的 stamp_id，印章可以通过调用 clearstamp(stamp_id) 来删除。', sig: '' },
  'clearstamp': { desc: '删除 stampid 指定的印章。', sig: 'stampid' },
  'clearstamps': { desc: '删除全部或前/后 n 个海龟印章。如果 n 为 None 则删除全部印章，如果 n > 0 则删除前 n 个印章，否则如果 n < 0 则删除后 n 个印章。', sig: 'n=None' },
  'undo': { desc: '撤消 (或连续撤消) 最近的一个 (或多个) 海龟动作。可撤消的次数由撤消缓冲区的大小决定。', sig: '' },
  'speed': { desc: '设置海龟移动的速度为 0..10 表示的整型数值。如未指定参数则返回当前速度。', sig: 'speed=None' },
  'position': { desc: '返回海龟当前的坐标 (x,y) (为 Vec2D 矢量类对象)。', sig: '' },
  'pos': { desc: '返回海龟当前的坐标 (x,y) (为 Vec2D 矢量类对象)。', sig: '' },
  'towards': { desc: '返回从海龟位置到由 (x,y)、矢量或另一海龟所确定位置的连线的夹角。 此数值依赖于海龟的初始朝向，这又取决于 "standard"/"world" 或 "logo" 模式设置。', sig: 'x, y=None' },
  'xcor': { desc: '返回海龟的 x 坐标。', sig: '' },
  'ycor': { desc: '返回海龟的 y 坐标。', sig: '' },
  'heading': { desc: '返回海龟当前的朝向 (数值依赖于海龟模式参见 mode())。', sig: '' },
  'distance': { desc: '返回从海龟位置到由 (x,y)，矢量或另一海龟对应位置的单位距离。', sig: 'x, y=None' },
  'degrees': { desc: '设置角度的度量单位，即设置一个圆周为多少 "度"。默认值为 360 度。', sig: 'fullcircle=360.0' },
  'radians': { desc: '设置角度的度量单位为弧度。其值等于 degrees(2math.pi)。', sig: '' },
  'pendown': { desc: '画笔落下 -- 移动时将画线。', sig: '' },
  'pd': { desc: '画笔落下 -- 移动时将画线。', sig: '' },
  'down': { desc: '画笔落下 -- 移动时将画线。', sig: '' },
  'penup': { desc: '画笔抬起 -- 移动时不画线。', sig: '' },
  'pu': { desc: '画笔抬起 -- 移动时不画线。', sig: '' },
  'up': { desc: '画笔抬起 -- 移动时不画线。', sig: '' },
  'pensize': { desc: '设置线条的粗细为 width 或返回该值。如果 resizemode 设为 "auto" 并且 turtleshape 为多边形，该多边形也以同样粗细的线条绘制。如未指定参数，则返回当前的 pensize。', sig: 'width=None' },
  'width': { desc: '设置线条的粗细为 width 或返回该值。如果 resizemode 设为 "auto" 并且 turtleshape 为多边形，该多边形也以同样粗细的线条绘制。如未指定参数，则返回当前的 pensize。', sig: 'width=None' },
  'pen': { desc: '返回或设置画笔的属性，以一个包含以下键值对的 "画笔字典" 表示', sig: 'pen=None, **pendict' },
  'isdown': { desc: '如果画笔落下返回 True，如果画笔抬起返回 False。', sig: '' },
  'pencolor': { desc: '返回或设置画笔颜色。', sig: 'color, /' },
  'fillcolor': { desc: '返回或设置填充颜色。', sig: 'color, /' },
  'color': { desc: '返回或设置画笔颜色和填充颜色。', sig: 'color, /' },
  'filling': { desc: '返回填充状态 (填充为 True，否则为 False)。', sig: '' },
  'fill': { desc: '填充在 with turtle.fill(): 块中绘制的形状。', sig: '' },
  'begin_fill': { desc: '在绘制要填充的形状之前调用。', sig: '' },
  'end_fill': { desc: '填充上次调用 begin_fill() 之后绘制的形状。', sig: '' },
  'reset': { desc: '从屏幕中删除海龟的绘图，海龟回到原点并设置所有变量为默认值。', sig: '' },
  'clear': { desc: '从屏幕中删除指定海龟的绘图。不移动海龟。海龟的状态和位置以及其他海龟的绘图不受影响。', sig: '' },
  'write': { desc: '基于 align ("left", "center" 或 "right") 并使用给定的字体将文本 —— arg 的字符串表示形式 —— 写到当前海龟位置。 如果 move 为真值，画笔会移至文本的右下角。 默认情况下 move 为 False。', sig: 'arg, move=False, align=\'left\', font=(\'Arial\', 8, \'normal\')' },
  'hideturtle': { desc: '使海龟不可见。当你绘制复杂图形时这是个好主意，因为隐藏海龟可显著加快绘制速度。', sig: '' },
  'ht': { desc: '使海龟不可见。当你绘制复杂图形时这是个好主意，因为隐藏海龟可显著加快绘制速度。', sig: '' },
  'showturtle': { desc: '使海龟可见。', sig: '' },
  'st': { desc: '使海龟可见。', sig: '' },
  'isvisible': { desc: '如果海龟显示返回 True，如果海龟隐藏返回 False。', sig: '' },
  'shape': { desc: '设置海龟形状为 name 指定的形状名，如未指定形状名则返回当前的形状名。name 指定的形状名应存在于 TurtleScreen 的 shape 字典中。多边形的形状初始时有以下几种: "arrow", "turtle", "circle", "square", "triangle", "classic"。要了解如何处理形状请参看 Screen 方法 register_shape()。', sig: 'name=None' },
  'resizemode': { desc: '设置大小调整模式为以下值之一: "auto", "user", "noresize"。如未指定 rmode 则返回当前的大小调整模式。不同的大小调整模式的效果如下', sig: 'rmode=None' },
  'shapesize': { desc: '返回或设置画笔的属性 x/y 拉伸因子和/或轮廓。 设置大小调整模式为 "user"。 当且仅当大小调整模式为 "user" 时，海龟会基于其拉伸因子调整外观: stretch_wid 为垂直于其朝向的宽度拉伸因子，stretch_len 为平行于其朝向的长度拉伸因子，outline 决定形状轮廓线的宽度。', sig: 'stretch_wid=None, stretch_len=None, outline=None' },
  'turtlesize': { desc: '返回或设置画笔的属性 x/y 拉伸因子和/或轮廓。 设置大小调整模式为 "user"。 当且仅当大小调整模式为 "user" 时，海龟会基于其拉伸因子调整外观: stretch_wid 为垂直于其朝向的宽度拉伸因子，stretch_len 为平行于其朝向的长度拉伸因子，outline 决定形状轮廓线的宽度。', sig: 'stretch_wid=None, stretch_len=None, outline=None' },
  'shearfactor': { desc: '设置或返回当前的剪切因子。根据 shear 指定的剪切因子即剪切角度的切线来剪切海龟形状。不 改变海龟的朝向 (移动方向)。如未指定 shear 参数: 返回当前的剪切因子即剪切角度的切线，与海龟朝向平行的线条将被剪切。', sig: 'shear=None' },
  'tilt': { desc: '海龟形状自其当前的倾角转动 angle 指定的角度，但 不 改变海龟的朝向 (移动方向)。', sig: 'angle' },
  'tiltangle': { desc: '设置或返回当前的倾角。如果指定 angle 则旋转海龟形状使其指向 angle 指定的方向，忽略其当前的倾角。不 改变海龟的朝向 (移动方向)。如果未指定 angle: 返回当前的倾角，即海龟形状的方向和海龟朝向 (移动方向) 之间的夹角。', sig: 'angle=None' },
  'shapetransform': { desc: '设置或返回海龟形状的当前变形矩阵。', sig: 't11=None, t12=None, t21=None, t22=None' },
  'get_shapepoly': { desc: '返回以坐标值对元组表示的当前形状多边形。这可以用于定义一个新形状或一个复合形状的多个组成部分。', sig: '' },
  'onrelease': { desc: '将 fun 指定的函数绑定到在此海龟上释放鼠标按键事件。如果 fun 值为 None，则移除现有的绑定。', sig: 'fun, btn=1, add=None' },
  'ondrag': { desc: '将 fun 指定的函数绑定到在此海龟上移动鼠标事件。如果 fun 值为 None，则移除现有的绑定。', sig: 'fun, btn=1, add=None' },
  'poly': { desc: '记录在 with turtle.poly(): 块中绘制的多边形的顶点。 第一个和最后一个顶点将被连接。', sig: '' },
  'begin_poly': { desc: '开始记录多边形的顶点。当前海龟位置为多边形的第一个顶点。', sig: '' },
  'end_poly': { desc: '停止记录多边形的顶点。当前海龟位置为多边形的最后一个顶点。它将连线到第一个顶点。', sig: '' },
  'get_poly': { desc: '返回最新记录的多边形。', sig: '' },
  'clone': { desc: '创建并返回海龟的克隆体，具有相同的位置、朝向和海龟属性。', sig: '' },
  'getturtle': { desc: '返回海龟对象自身。唯一合理的用法: 作为一个函数来返回 "匿名海龟"', sig: '' },
  'getpen': { desc: '返回海龟对象自身。唯一合理的用法: 作为一个函数来返回 "匿名海龟"', sig: '' },
  'getscreen': { desc: '返回作为海龟绘图场所的 TurtleScreen 类对象。该对象将可调用 TurtleScreen 方法。', sig: '' },
  'setundobuffer': { desc: '设置或禁用撤销缓冲区。 如果 size 为整数，则开辟一个给定大小的空撤销缓冲区。 size 给出了可以通过 undo() 方法/函数撤销海龟动作的最大次数。 如果 size 为 None，则禁用撤销缓冲区。', sig: 'size' },
  'undobufferentries': { desc: '返回撤销缓冲区里的条目数。', sig: '' },
  'bgcolor': { desc: '返回或设置 TurtleScreen 的背景颜色。', sig: 'color, /' },
  'bgpic': { desc: '设置背景图片或返回当前背景图片名称。如果 picname 为一个文件名，则将相应图片设为背景。如果 picname 为 "nopic"，则删除当前背景图片。如果 picname 为 None，则返回当前背景图片文件名。', sig: 'picname=None' },
  'clearscreen': { desc: '从中删除所有海龟的全部绘图。将已清空的 TurtleScreen 重置为初始状态: 白色背景，无背景图片，无事件绑定并启用追踪。', sig: '' },
  'resetscreen': { desc: '重置屏幕上的所有海龟为其初始状态。', sig: '' },
  'screensize': { desc: '如未指定任何参数，则返回当前的 (canvaswidth, canvasheight)。否则改变作为海龟绘图场所的画布大小。不改变绘图窗口。要观察画布的隐藏区域，可以使用滚动条。通过此方法可以令之前绘制于画布之外的图形变为可见。', sig: 'canvwidth=None, canvheight=None, bg=None' },
  'setworldcoordinates': { desc: '设置用户自定义坐标系并在必要时切换模式为 "world"。这会执行一次 screen.reset()。如果 "world" 模式已激活，则所有图形将根据新的坐标系重绘。', sig: 'llx, lly, urx, ury' },
  'no_animation': { desc: '暂时禁用海龟动画。 在 no_animation 块内编写的代码将不会被动画化；一旦代码块退出，绘图就会出现。', sig: '' },
  'delay': { desc: '设置或返回以毫秒数表示的延迟值 delay。(这约等于连续两次画布刷新的间隔时间。) 绘图延迟越长，动画速度越慢。', sig: 'delay=None' },
  'tracer': { desc: '启用/禁用海龟动画并设置刷新图形的延迟时间。如果指定 n 值，则只有每第 n 次屏幕刷新会实际执行。(可被用来加速复杂图形的绘制。) 如果调用时不带参数，则返回当前保存的 n 值。第二个参数设置延迟值 (参见 delay())。', sig: 'n=None, delay=None' },
  'update': { desc: '执行一次 TurtleScreen 刷新。在禁用追踪时使用。', sig: '' },
  'listen': { desc: '设置焦点到 TurtleScreen (以便接收按键事件)。使用两个 Dummy 参数以便能够传递 listen() 给 onclick 方法。', sig: 'xdummy=None, ydummy=None' },
  'onkey': { desc: '绑定 fun 指定的函数到按键释放事件。如果 fun 值为 None，则移除事件绑定。注: 为了能够注册按键事件，TurtleScreen 必须得到焦点。(参见 listen() 方法。)', sig: 'fun, key' },
  'onkeyrelease': { desc: '绑定 fun 指定的函数到按键释放事件。如果 fun 值为 None，则移除事件绑定。注: 为了能够注册按键事件，TurtleScreen 必须得到焦点。(参见 listen() 方法。)', sig: 'fun, key' },
  'onkeypress': { desc: '绑定 fun 指定的函数到指定键的按下事件。如未指定键则绑定到任意键的按下事件。注: 为了能够注册按键事件，必须得到焦点。(参见 listen() 方法。)', sig: 'fun, key=None' },
  'onclick': { desc: '绑定 fun 指定的函数到鼠标点击屏幕事件。如果 fun 值为 None，则移除现有的绑定。', sig: 'fun, btn=1, add=None' },
  'onscreenclick': { desc: '绑定 fun 指定的函数到鼠标点击屏幕事件。如果 fun 值为 None，则移除现有的绑定。', sig: 'fun, btn=1, add=None' },
  'ontimer': { desc: '安装一个计时器，在 t 毫秒后调用 fun 函数。', sig: 'fun, t=0' },
  'mainloop': { desc: '开始事件循环 - 调用 Tkinter 的 mainloop 函数。必须作为一个海龟绘图程序的结束语句。如果一个脚本是在以 -n 模式 (无子进程) 启动的 IDLE 中运行时 不可 使用 - 用于实现海龟绘图的交互功能。', sig: '' },
  'done': { desc: '开始事件循环 - 调用 Tkinter 的 mainloop 函数。必须作为一个海龟绘图程序的结束语句。如果一个脚本是在以 -n 模式 (无子进程) 启动的 IDLE 中运行时 不可 使用 - 用于实现海龟绘图的交互功能。', sig: '' },
  'textinput': { desc: '弹出一个对话框窗口用来输入一个字符串。形参 title 为对话框窗口的标题，prompt 为一条文本，通常用来提示要输入什么信息。返回输入的字符串。如果对话框被取消则返回 None。', sig: 'title, prompt' },
  'numinput': { desc: '弹出一个用于输入数值的对话框窗口。 title 是对话框窗口的标题，prompt 是通常用来描述要输入的数字信息的文本。 default: 默认值, minval: 可输入的最小值, maxval: 可输入的最大值。 如果给出 minval .. maxval 则输入的数值必须在此范围以内。 如未给出，则将发出提示并且对话框保持打开以便修正。 返回输入的数值。 如果对话框被取消，则返回 None。', sig: 'title, prompt, default=None, minval=None, maxval=None' },
  'mode': { desc: '设置海龟模式 ("standard", "logo" 或 "world") 并执行重置。如未指定模式则返回当前的模式。', sig: 'mode=None' },
  'colormode': { desc: '返回 colormode 或将其设为 1.0 或 255。 后续表示三原色的 r, g, b 值必须在 0..cmode 范围之内。', sig: 'cmode=None' },
  'getcanvas': { desc: '返回此 TurtleScreen 的 Canvas 对象。供了解 Tkinter 的 Canvas 对象内部机理的人士使用。', sig: '' },
  'getshapes': { desc: '返回所有当前可用海龟形状的列表。', sig: '' },
  'register_shape': { desc: '调用此函数有四种不同方式', sig: 'name, shape=None' },
  'addshape': { desc: '调用此函数有四种不同方式', sig: 'name, shape=None' },
  'turtles': { desc: '返回屏幕上的海龟列表。', sig: '' },
  'window_height': { desc: '返回海龟窗口的高度。', sig: '' },
  'window_width': { desc: '返回海龟窗口的宽度。', sig: '' },
  'bye': { desc: '关闭海龟绘图窗口。', sig: '' },
  'exitonclick': { desc: '将 bye() 方法绑定到 Screen 上的鼠标点击事件。', sig: '' },
  'save': { desc: '将当前海龟绘图（和海龟）另存为PostScript文件。', sig: 'filename, overwrite=False' },
  'setup': { desc: '设置主窗口的大小和位置。默认参数值保存在配置字典中，可通过 turtle.cfg 文件进行修改。', sig: 'width=_CFG[\'width\'], height=_CFG[\'height\'], startx=_CFG[\'leftright\'], starty=_CFG[\'topbottom\']' },
  'title': { desc: '设置海龟窗口标题为 titlestring 指定的文本。', sig: 'titlestring' },
  'write_docstringdict': { desc: '创建文档字符串字典并将其写入 filename 指定的 Python 脚本文件。此函数必须显式地调用 (海龟绘图类并不使用此函数)。文档字符串字典将被写入到 Python 脚本文件 filename.py。该文件可作为模板用来将文档字符串翻译为不同语言。', sig: 'filename=\'turtle_docstringdict\'' },
}
